// Generated by generate_data.py. Local paths are relative to src/index.html.
window.DEMO_DATA = {
  "experiment": {
    "transcript": "Hello, how are you today? <laughter> It is so good to see you!",
    "clips": [
      {
        "id": "source",
        "label": "Source audio",
        "image": "../data/experiment/20260917-091055-272786_seed-phase/source.spectrogram.viridis.plain.png",
        "audio": "../data/experiment/20260917-091055-272786_seed-phase/source.wav",
        "duration": 9.504
      },
      {
        "id": "seed_42",
        "label": "Seed 42",
        "image": "../data/experiment/20260917-091055-272786_seed-phase/seed_42.spectrogram.viridis.plain.png",
        "audio": "../data/experiment/20260917-091055-272786_seed-phase/seed_42.wav",
        "duration": 9.504
      },
      {
        "id": "seed_1235",
        "label": "Seed 1235",
        "image": "../data/experiment/20260917-091055-272786_seed-phase/seed_1235.spectrogram.viridis.plain.png",
        "audio": "../data/experiment/20260917-091055-272786_seed-phase/seed_1235.wav",
        "duration": 9.504
      }
    ]
  },
  "methods": [
    {
      "id": "source",
      "label": "Source",
      "kind": "Original"
    },
    {
      "id": "tts",
      "label": "TTS",
      "kind": "Benchmark"
    },
    {
      "id": "seed-vc",
      "label": "Seed-VC",
      "kind": "Benchmark"
    },
    {
      "id": "vevo-voice",
      "label": "Vevo-Voice",
      "kind": "Benchmark"
    },
    {
      "id": "rhythmic-noise",
      "label": "Rhythmic Noise",
      "kind": "Ours"
    }
  ],
  "samples": [
    {
      "id": "ada-yonath-1",
      "name": "Ada Yonath",
      "transcript": "Crystallography is the only method that can bring very, very accurate molecular wa, eh, molecular level information.",
      "videos": {
        "source": {
          "src": "../data/videos/ada-yonath-1/source.mp4",
          "poster": "assets/posters/ada-yonath-1-source.jpg",
          "duration": 10.261
        },
        "tts": {
          "src": "../data/videos/ada-yonath-1/tts/converted.mp4",
          "poster": "assets/posters/ada-yonath-1-tts.jpg",
          "duration": 10.25
        },
        "seed-vc": {
          "src": "../data/videos/ada-yonath-1/seed-vc/ada-yonath-1_54d1705d__chunk_00000__p225/converted.mp4",
          "poster": "assets/posters/ada-yonath-1-seed-vc.jpg",
          "duration": 10.519
        },
        "vevo-voice": {
          "src": "../data/videos/ada-yonath-1/vevo-voice/ada-yonath-1_54d1705d__p225/converted.mp4",
          "poster": "assets/posters/ada-yonath-1-vevo-voice.jpg",
          "duration": 10.25
        },
        "rhythmic-noise": {
          "src": "../data/videos/ada-yonath-1/rhythmic-noise/ada-yonath-1_54d1705d__phase-0.5_band-0-0.3_mag-0.8_cfg-3_ref-3__mag-0_phase-0-0.3_cfg-3_seed-42_gain-0.8-0.8_ref-3_phase-weight-0.5-0_phase-band_voice-p225_b3eaf2b4/converted.mp4",
          "poster": "assets/posters/ada-yonath-1-rhythmic-noise.jpg",
          "duration": 10.25
        }
      }
    },
    {
      "id": "bernard-scholkopf-4",
      "name": "Bernhard Schölkopf",
      "transcript": "And then just by a strike of luck last September it turned out one of those planets made the news because others found out that this was the very first planet in the habitable zone around its star, meaning in the right distance such that water could be liquid.",
      "videos": {
        "source": {
          "src": "../data/videos/bernard-scholkopf-4/source.mp4",
          "poster": "assets/posters/bernard-scholkopf-4-source.jpg",
          "duration": 16.128
        },
        "tts": {
          "src": "../data/videos/bernard-scholkopf-4/tts/converted.mp4",
          "poster": "assets/posters/bernard-scholkopf-4-tts.jpg",
          "duration": 16.12
        },
        "seed-vc": {
          "src": "../data/videos/bernard-scholkopf-4/seed-vc/bernard-scholkopf-4_39eea3b2__chunk_00000__p226/converted.mp4",
          "poster": "assets/posters/bernard-scholkopf-4-seed-vc.jpg",
          "duration": 16.12
        },
        "vevo-voice": {
          "src": "../data/videos/bernard-scholkopf-4/vevo-voice/bernard-scholkopf-4_39eea3b2__p226/converted.mp4",
          "poster": "assets/posters/bernard-scholkopf-4-vevo-voice.jpg",
          "duration": 16.12
        },
        "rhythmic-noise": {
          "src": "../data/videos/bernard-scholkopf-4/rhythmic-noise/bernard-scholkopf-4_39eea3b2__phase-0.5_band-0-0.3_mag-0.8_cfg-8_ref-3__mag-0_phase-0-0.3_cfg-3_seed-42_gain-0.8-0.8_ref-3_phase-weight-0.5-0_phase-band_voice-p226_696debd1/converted.mp4",
          "poster": "assets/posters/bernard-scholkopf-4-rhythmic-noise.jpg",
          "duration": 16.12
        }
      }
    },
    {
      "id": "emmanuelle-chapentier-3",
      "name": "Emmanuelle Charpentier",
      "transcript": "And then when you, when you start to understand the biological world, and specifically when you start to understand the microbial world, you also understand that the microbes work quite much as, you know, you find a lot of sociological aspects in the microbial world that are quite similar to our world.",
      "videos": {
        "source": {
          "src": "../data/videos/emmanuelle-chapentier-3/source.mp4",
          "poster": "assets/posters/emmanuelle-chapentier-3-source.jpg",
          "duration": 22.763
        },
        "tts": {
          "src": "../data/videos/emmanuelle-chapentier-3/tts/converted.mp4",
          "poster": "assets/posters/emmanuelle-chapentier-3-tts.jpg",
          "duration": 22.76
        },
        "seed-vc": {
          "src": "../data/videos/emmanuelle-chapentier-3/seed-vc/emmanuelle-charpentier-3_61e36d74__chunk_00000__p228/converted.mp4",
          "poster": "assets/posters/emmanuelle-chapentier-3-seed-vc.jpg",
          "duration": 22.76
        },
        "vevo-voice": {
          "src": "../data/videos/emmanuelle-chapentier-3/vevo-voice/emmanuelle-charpentier-3_61e36d74__p228/converted.mp4",
          "poster": "assets/posters/emmanuelle-chapentier-3-vevo-voice.jpg",
          "duration": 22.76
        },
        "rhythmic-noise": {
          "src": "../data/videos/emmanuelle-chapentier-3/rhythmic-noise/emmanuelle-charpentier-3_61e36d74__phase-0.5_band-0-0.3_mag-0.8_cfg-3_ref-3__mag-0_phase-0-0.3_cfg-3_seed-42_gain-0.8-0.8_ref-3_phase-weight-0.5-0_phase-band_voice-p228_0a067b03/converted.mp4",
          "poster": "assets/posters/emmanuelle-chapentier-3-rhythmic-noise.jpg",
          "duration": 22.76
        }
      }
    },
    {
      "id": "han-kang-1",
      "name": "Han Kang",
      "transcript": "it was not just writer's block it was like I couldn't read fiction",
      "videos": {
        "source": {
          "src": "../data/videos/han-kang-1/source.mp4",
          "poster": "assets/posters/han-kang-1-source.jpg",
          "duration": 12.139
        },
        "tts": {
          "src": "../data/videos/han-kang-1/tts/converted.mp4",
          "poster": "assets/posters/han-kang-1-tts.jpg",
          "duration": 12.12
        },
        "seed-vc": {
          "src": "../data/videos/han-kang-1/seed-vc/han-kang-1_7477bb9c__chunk_00000__p228/converted.mp4",
          "poster": "assets/posters/han-kang-1-seed-vc.jpg",
          "duration": 12.12
        },
        "vevo-voice": {
          "src": "../data/videos/han-kang-1/vevo-voice/han-kang-1_7477bb9c__p228/converted.mp4",
          "poster": "assets/posters/han-kang-1-vevo-voice.jpg",
          "duration": 12.12
        },
        "rhythmic-noise": {
          "src": "../data/videos/han-kang-1/rhythmic-noise/han-kang-1_7477bb9c__phase-0.5_band-0-0.3_mag-0.8_cfg-8_ref-3__mag-0_phase-0-0.3_cfg-3_seed-42_gain-0.8-0.8_ref-3_phase-weight-0.5-0_phase-band_voice-p228_0a067b03/converted.mp4",
          "poster": "assets/posters/han-kang-1-rhythmic-noise.jpg",
          "duration": 12.12
        }
      }
    },
    {
      "id": "junichi-yamagishi-5",
      "name": "Junichi Yamagishi",
      "transcript": "The theme of Interspeech two thousand twenty six is Speaking Together. That is how this field has always made progress. I hope to see you in Sydney.",
      "videos": {
        "source": {
          "src": "../data/videos/junichi-yamagishi-5/source.mp4",
          "poster": "assets/posters/junichi-yamagishi-5-source.jpg",
          "duration": 11.904
        },
        "tts": {
          "src": "../data/videos/junichi-yamagishi-5/tts/converted.mp4",
          "poster": "assets/posters/junichi-yamagishi-5-tts.jpg",
          "duration": 11.9
        },
        "seed-vc": {
          "src": "../data/videos/junichi-yamagishi-5/seed-vc/junichi-yamagishi-5_a94d3343__chunk_00000__p226/converted.mp4",
          "poster": "assets/posters/junichi-yamagishi-5-seed-vc.jpg",
          "duration": 12.504
        },
        "vevo-voice": {
          "src": "../data/videos/junichi-yamagishi-5/vevo-voice/junichi-yamagishi-5_a94d3343__p226/converted.mp4",
          "poster": "assets/posters/junichi-yamagishi-5-vevo-voice.jpg",
          "duration": 11.9
        },
        "rhythmic-noise": {
          "src": "../data/videos/junichi-yamagishi-5/rhythimic-noise/junichi-yamagishi-5_a94d3343__phase-0.5_band-0-0.3_mag-0.8_cfg-8_ref-3__mag-0_phase-0-0.3_cfg-3_seed-42_gain-0.8-0.8_ref-3_phase-weight-0.5-0_phase-band_voice-p226_696debd1/converted.mp4",
          "poster": "assets/posters/junichi-yamagishi-5-rhythmic-noise.jpg",
          "duration": 11.9
        }
      }
    },
    {
      "id": "nusslein-vohard-2",
      "name": "Christiane Nüsslein-Volhard",
      "transcript": "You can count segments and you can see, and we had some, and we had a strange rule that every other segment was hit in one class of mutants in different manners, and then we had another class where the segment showed duplicated polarity of the tentacle bands.",
      "videos": {
        "source": {
          "src": "../data/videos/nusslein-vohard-2/source.mp4",
          "poster": "assets/posters/nusslein-vohard-2-source.jpg",
          "duration": 18.923
        },
        "tts": {
          "src": "../data/videos/nusslein-vohard-2/tts/converted.mp4",
          "poster": "assets/posters/nusslein-vohard-2-tts.jpg",
          "duration": 18.92
        },
        "seed-vc": {
          "src": "../data/videos/nusslein-vohard-2/seed-vc/nusslein-volhard-2_866238ae__chunk_00000__p225/converted.mp4",
          "poster": "assets/posters/nusslein-vohard-2-seed-vc.jpg",
          "duration": 18.92
        },
        "vevo-voice": {
          "src": "../data/videos/nusslein-vohard-2/vevo-voice/nusslein-volhard-2_866238ae__p225/converted.mp4",
          "poster": "assets/posters/nusslein-vohard-2-vevo-voice.jpg",
          "duration": 18.92
        },
        "rhythmic-noise": {
          "src": "../data/videos/nusslein-vohard-2/rhythmic-noise/nusslein-volhard-2_866238ae__phase-0.5_band-0-0.3_mag-0.8_cfg-8_ref-3__mag-0_phase-0-0.3_cfg-3_seed-42_gain-0.8-0.8_ref-3_phase-weight-0.5-0_phase-band_voice-p225_b3eaf2b4/converted.mp4",
          "poster": "assets/posters/nusslein-vohard-2-rhythmic-noise.jpg",
          "duration": 18.92
        }
      }
    },
    {
      "id": "olga-tokaczuk-1",
      "name": "Olga Tokarczuk",
      "transcript": "Designed to catch our attention, but they are not working as a process. As the human minds are accustomed to be in process all the time.",
      "videos": {
        "source": {
          "src": "../data/videos/olga-tokaczuk-1/source.mp4",
          "poster": "assets/posters/olga-tokaczuk-1-source.jpg",
          "duration": 10.923
        },
        "tts": {
          "src": "../data/videos/olga-tokaczuk-1/tts/converted.mp4",
          "poster": "assets/posters/olga-tokaczuk-1-tts.jpg",
          "duration": 10.92
        },
        "seed-vc": {
          "src": "../data/videos/olga-tokaczuk-1/seed-vc/olga-tokaczuk-1_f9769893__chunk_00000__p228/converted.mp4",
          "poster": "assets/posters/olga-tokaczuk-1-seed-vc.jpg",
          "duration": 11.227
        },
        "vevo-voice": {
          "src": "../data/videos/olga-tokaczuk-1/vevo-voice/olga-tokaczuk-1_f9769893__p228/converted.mp4",
          "poster": "assets/posters/olga-tokaczuk-1-vevo-voice.jpg",
          "duration": 10.92
        },
        "rhythmic-noise": {
          "src": "../data/videos/olga-tokaczuk-1/rhythmic-noise/olga-tokaczuk-1_f9769893__phase-0.5_band-0-0.3_mag-0.8_cfg-8_ref-3__mag-0_phase-0-0.3_cfg-3_seed-42_gain-0.8-0.8_ref-3_phase-weight-0.5-0_phase-band_voice-p228_0a067b03/converted.mp4",
          "poster": "assets/posters/olga-tokaczuk-1-rhythmic-noise.jpg",
          "duration": 10.92
        }
      }
    },
    {
      "id": "shing-tung-yau-1",
      "name": "Shing-Tung Yau",
      "transcript": "As long as you come up with something I feel I can do better than you, I can find new idea or new direction or new method, I can be better than you.",
      "videos": {
        "source": {
          "src": "../data/videos/shing-tung-yau-1/source.mp4",
          "poster": "assets/posters/shing-tung-yau-1-source.jpg",
          "duration": 13.248
        },
        "tts": {
          "src": "../data/videos/shing-tung-yau-1/tts/converted.mp4",
          "poster": "assets/posters/shing-tung-yau-1-tts.jpg",
          "duration": 13.24
        },
        "seed-vc": {
          "src": "../data/videos/shing-tung-yau-1/seed-vc/shing-tung-yau-1_950cc787__chunk_00000__p226/converted.mp4",
          "poster": "assets/posters/shing-tung-yau-1-seed-vc.jpg",
          "duration": 13.386
        },
        "vevo-voice": {
          "src": "../data/videos/shing-tung-yau-1/vevo-voice/shing-tung-yau-1_950cc787__p226/converted.mp4",
          "poster": "assets/posters/shing-tung-yau-1-vevo-voice.jpg",
          "duration": 13.24
        },
        "rhythmic-noise": {
          "src": "../data/videos/shing-tung-yau-1/rhythmic-noise/shing-tung-yau-1_950cc787__phase-0.5_band-0-0.3_mag-0.8_cfg-8_ref-3__mag-0_phase-0-0.3_cfg-3_seed-42_gain-0.8-0.8_ref-3_phase-weight-0.5-0_phase-band_voice-p226_696debd1/converted.mp4",
          "poster": "assets/posters/shing-tung-yau-1-rhythmic-noise.jpg",
          "duration": 13.24
        }
      }
    },
    {
      "id": "yann-lecun-3",
      "name": "Yann LeCun",
      "transcript": "So, you know, it's not just around the corner. I mean, I've been hearing people for the last 12, 15 years claiming that, you know, AGI is just around the corner and being systematically wrong. And I knew they were wrong when they were saying it. I called their bullshit <laughter>.",
      "videos": {
        "source": {
          "src": "../data/videos/yann-lecun-3/yann-lecun-3.mp4",
          "poster": "assets/posters/yann-lecun-3-source.jpg",
          "duration": 17.344
        },
        "tts": {
          "src": "../data/videos/yann-lecun-3/tts/converted.mp4",
          "poster": "assets/posters/yann-lecun-3-tts.jpg",
          "duration": 17.333
        },
        "seed-vc": {
          "src": "../data/videos/yann-lecun-3/seed-vc/yann-lecun-3_97b1f6ba__chunk_00000__p226/converted.mp4",
          "poster": "assets/posters/yann-lecun-3-seed-vc.jpg",
          "duration": 17.333
        },
        "vevo-voice": {
          "src": "../data/videos/yann-lecun-3/vevo-voice/yann-lecun-3_97b1f6ba__p226/converted.mp4",
          "poster": "assets/posters/yann-lecun-3-vevo-voice.jpg",
          "duration": 17.333
        },
        "rhythmic-noise": {
          "src": "../data/videos/yann-lecun-3/rhythmic-noise/yann-lecun-3_97b1f6ba__phase-0.5_band-0-0.3_mag-0.8_cfg-8_ref-3__mag-0_phase-0-0.3_cfg-3_seed-42_gain-0.8-0.8_ref-3_phase-weight-0.5-0_phase-band_voice-p226_696debd1/converted.mp4",
          "poster": "assets/posters/yann-lecun-3-rhythmic-noise.jpg",
          "duration": 17.333
        }
      }
    },
    {
      "id": "yuh-jong-youn-5",
      "name": "Yuh-Jung Youn",
      "transcript": "Very difficult for me. I'm pure Korean. I couldn't speak English, so",
      "videos": {
        "source": {
          "src": "../data/videos/yuh-jong-youn-5/source.mp4",
          "poster": "assets/posters/yuh-jong-youn-5-source.jpg",
          "duration": 6.72
        },
        "tts": {
          "src": "../data/videos/yuh-jong-youn-5/tts/converted.mp4",
          "poster": "assets/posters/yuh-jong-youn-5-tts.jpg",
          "duration": 6.707
        },
        "seed-vc": {
          "src": "../data/videos/yuh-jong-youn-5/seed-vc/yuh-jung-youn-5_32339de8__chunk_00000__p225/converted.mp4",
          "poster": "assets/posters/yuh-jong-youn-5-seed-vc.jpg",
          "duration": 6.707
        },
        "vevo-voice": {
          "src": "../data/videos/yuh-jong-youn-5/vevo-voice/yuh-jung-youn-5_32339de8__p225/converted.mp4",
          "poster": "assets/posters/yuh-jong-youn-5-vevo-voice.jpg",
          "duration": 6.707
        },
        "rhythmic-noise": {
          "src": "../data/videos/yuh-jong-youn-5/rhythmic-noise/yuh-jung-youn-5_32339de8__phase-0.5_band-0-0.3_mag-0.8_cfg-8_ref-3__mag-0_phase-0-0.3_cfg-3_seed-42_gain-0.8-0.8_ref-3_phase-weight-0.5-0_phase-band_voice-p225_b3eaf2b4/converted.mp4",
          "poster": "assets/posters/yuh-jong-youn-5-rhythmic-noise.jpg",
          "duration": 6.707
        }
      }
    }
  ]
};
